### ISSUE TITLE
facing issue while running the command

### ISSUE THREAD

**Issue by nischaysingla** [ashishb/adb-enhanced#5] opened 2018-07-06 13:26 UTC
./adbe: No such file or directory

**Comment by ashishb** [comment] 2018-07-06 16:23
Did you try "sudo pip install adb-enhanced"? Calling this without sudo
doesn't put the binary in the bin directory for me.

**Comment by kaciula** [comment] 2018-07-07 10:55
I think the issue is that you are running the command in your current directory ( ./adbe ). You should run the command without the "./" prefix.

**Comment by ashishb** [comment] 2018-07-15 18:38
I added "sudo" to the installation step. Marking this as closed.

**Closed by ashishb** 2018-07-15 18:38 UTC
